before_install:
  - gem update cocoapods --no-document --pre
  - gem update fastlane --no-document
  - fastlane --version
  - gem cleanup
  - brew outdated xctool || brew upgrade xctool
  - pod --version
  - pod repo update --silent
language: objective-c
osx_image: xcode8
script:
  # - fastlane travis
  - xcodebuild -workspace "Dodies.lv.xcworkspace" -scheme "Dodies.lv" -configuration "Debug" clean build CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
notifications: change